operator:
  develop: # only for develop purposes, in production use wiretap=false, proxy.active=false and skipssl=true
    httpclient:
      wiretap: true
      proxy:
        active: false
        host: localhost
        port: 7777
      skipssl: false #typically you have to set skipssl to false if the proxy is active


